name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: verify
      run: ls -l
    - name: compile
      run: cc -g foo.c -o foo
    - name: run-app
      run: ./foo
